table 'Dim Date'
	dataCategory: Time

	column 'date_key'
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: date_key

	column 'date'
		dataType: date
		summarizeBy: none
		sourceColumn: date

	column 'year'
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column 'quarter'
		dataType: string
		summarizeBy: none
		sourceColumn: quarter

	column 'month_number'
		dataType: int64
		summarizeBy: none
		sourceColumn: month_number

	column 'month_name'
		dataType: string
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

	column 'year_month'
		dataType: string
		summarizeBy: none
		sourceColumn: year_month

	column 'day_of_week_number'
		dataType: int64
		summarizeBy: none
		sourceColumn: day_of_week_number

	column 'day_of_week'
		dataType: string
		summarizeBy: none
		sourceColumn: day_of_week
		sortByColumn: day_of_week_number

	column 'is_weekend'
		dataType: logical
		summarizeBy: none
		sourceColumn: is_weekend

	partition 'Dim Date' = m
		mode: import
		source =
			let
				Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/agbajames/manufacturing-operations-analytics/main/data/processed/dim_date.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", type text}, {"month_number", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"day_of_week_number", Int64.Type}, {"day_of_week", type text}, {"is_weekend", type logical}}, "en-GB")
			in
				Typed
